FROM container-base:local

LABEL maintainer="Nate Groebner"

USER ${NB_UID}
WORKDIR "${HOME}"

COPY . specufex
RUN cd "${HOME}"/specufex \
    && python -m pip install . \
    && docker-clean

# for password setup - only for 2024 Seattle SSA
# COPY .secrets/jupyter_server_config.json .jupyter/

WORKDIR "${HOME}/specufex/tutorials"

EXPOSE 8888
