name: Build


on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install .
      - name: Lint with flake8, black, isort
        run: |
          # stop the build if there are Python syntax errors or undefined names
          # flake8 specufex --count --extend-ignore=E203 --show-source --statistics --max-line-length=88
          # flake8 tests --count --extend-ignore=E203 --show-source --statistics --max-line-length=88
          # flake8 --count --show-source --statistics
          # black . --check
          # isort . --check
      - name: Test with pytest
        run: |
          pytest
